### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by thebabush** [thebabush/python-hfuzz#1]
- [ ] rewrite a afl-unicorn example to work with this
- [ ] test QBDI and hope it doesn't crash due to all the magic going on
- [ ] experiment with `sys.settrace` for simple coverage
- [ ] test integration with honggfuzz somehow
